
Initial Code
```{r}
library(readr)
library(tidyverse)
library(naniar)
library(ggplot2)
library(ggmosaic)
library(ggpubr)
library(gridExtra)
library(ggalluvial)
library(plyr)

initial <- read_csv("Data/aespanel.csv")
restricted <- read_csv("Data/Restricted Data.csv")
australian_postcodes <- read_csv("Data/australian_postcodes.csv")
PostcodePopulation <- read_csv("Data/PostcodePopulation.csv")
```

Improve comprehension of column headings
```{r}
part1 <- c('interest', 'attention_paper', 'attention_tv', 'attention_radio', 'attention_internet', 'interest_campaign', 'discuss_person', 'discuss_internet', 'persuade', 'show_support', 'rallies', 'donate', 'candidate_contact', 'contact_phone', 'contact_mail', 'contact_person', 'contact_text', 'contact_email', 'contact_internet', 'candidate_skipped', 'no_party', 'contact_liberal', 'contact_labor', 'contact_national', 'contact_greens', 'contact_other', 'candidate_skipped2', 'compulsory', 'would_vote', 'voting_age', 'media_usage', 'mainstream_news', 'online_content', 'federal_sites', 'electoral_site', 'media_none', 'media_skipped', 'follow_online', 'online_group', 'online_none', 'online_skipped', 'affiliation', 'support_other', 'support_strength', 'care_result', 'decision_time', 'vote_importance', 'majority_control', 'party_difference', 'left_right', 'scale_liberal', 'scale_labor', 'scale_national', 'scale_greens', 'vote_house', 'vote_senate', 'other_house', 'other_senate', 'vote_time', 'secondpref_house', 'secondpref_senate', 'howtovote', 'change_house', 'last_election_house', 'last_vote_sameparty', 'last_vote_liberal', 'last_vote_labor', 'last_vote_national', 'last_vote_green', 'last_vote_other', 'last_vote_first', 'last_vote_skipped', 'care_people', 'necessity', 'view_liberal', 'view_labor', 'view_national', 'view_greens', 'view_shorten', 'view_turnball', 'view_dinatale', 'shorten_intelligent', 'shorten_compassion', 'shorten_competent', 'shorten_sensible', 'shorten_leadership', 'shorten_honest', 'shorten_knowledgeable', 'shorten_inspiring', 'shorten_trustworthy', 'liberal_leader_change', 'view_democracy', 'government_interests', 'publicvsbig_interest', 'views_contact_email', 'views_contact_person', 'views_protest', 'views_worked', 'views_petition_written', 'views_petition_online', 'politicians_ordinary', 'power_importance', 'voting_importance', 'women_mps', 'importance_taxation', 'importance_immigration', 'importance_education', 'importance_environment', 'importance_debt', 'importance_health', 'importance_refugees', 'importance_climate', 'importance_superannuation', 'importance_economy', 'party_taxation', 'party_immigration', 'party_education', 'party_environment', 'party_debt', 'party_health', 'party_refugees', 'party_climate', 'party_superannuation', 'party_economy', 'issue_importance', 'issue_importance2', 'financial_situation', 'economic_situation', 'policy_financial', 'policy_economy', 'financial_future', 'economic_future', 'policy_financial_future', 'policy_economic_future', 'spending_health', 'spending_education', 'spending_unemployment', 'spending_defence', 'spending_pensions', 'spending_business', 'spending_police', 'spending_disability', 'spending_transport', 'spending_childcare', 'job_ease', 'job_ease_partner', 'hightax', 'unions', 'bigbusiness', 'wealth_redistribute', 'union_laws', 'view_income_difference', 'tax_socialservices', 'migrant_equality', 'nudity', 'land_rights', 'women_equality', 'migrant_numbers', 'gov_help_aborigines', 'asia_relations', 'abortion', 'same_sex_marriage', 'refugee_management', 'death_penalty', 'marijuana', 'criminal_sentences', 'women_job_pref', 'turn_back_boats', 'euthanasia', 'women_business', 'constitution_indigenous', 'aus_future_aim', 'aus_aim_second', 'royalty', 'republic', 'us_relations_security', 'us_defence', 'threat_japan', 'threat_us', 'threat_china', 'threat_vietnam', 'threat_malaysia', 'threat_indonesia', 'defence_situation', 'defence_trust', 'asia_trade', 'war_on_terror', 'immigrant_numbers', 'immigrant_crime', 'immigrant_economy', 'immigrant_jobs', 'immigrant_culture', 'climate_change', 'federation', 'house_reps', 'constitution', 'senate_election', 'parliament_fee', 'election_time', 'age_leaver', 'tertiary_study', 'qualifications', 'last_week', 'lastweek_other', 'worked_pay', 'job_title', 'job_tasks', 'job_business', 'job_type', 'job_position', 'employer', 'supervisor', 'union_member', 'sex', 'birth_year', 'birth_country', 'mother_country')
part2 <- c('father_country', 'indigenous_identity', 'father_preference', 'mother_preference', 'religion', 'religion_other', 'religious_services', 'marital_status', 'dwelling_status', 'invest_properties', 'superannuation_management', 'social_class', 'living_status', 'annual_income', 'shares', 'survey_participation', 'partner_last_week', 'partner_lastweek_other', 'partner_worked_pay', 'partner_job_title', 'partner_job_tasks', 'partner_job_type', 'partner_job_business', 'partner_employer', 'partner_supervisor', 'partner_union_member', 'partner_affiliation', 'partner_other', 'enrollment')

questions <- c(part1, part2)
question_data <- initial
colnames(question_data)[c(7:252)] <- questions
```

Create data sets specialised for issues
```{r fig.height=10, fig.width=10}
importance <- question_data[,c(1:2, 61, 111:132)]
importance$secondpref <- question_data$secondpref_house
importance$secondpref[is.na(importance$secondpref)] <- 999
importance[3:25] <- importance[3:25] %>% replace_with_na_all(condition = ~.x > 500) #https://cran.r-project.org/web/packages/naniar/vignettes/replace-with-na.html 
importance <- na.omit(importance)
importance[26] <- importance[26] %>% replace_with_na_all(condition = ~.x >500)
#https://www.programmingr.com/examples/remove-na-rows-in-r/#:~:text=The%20na.,in%20the%20R%20programming%20language.
importance[sapply(importance, is.numeric)] <- lapply(importance[sapply(importance, is.numeric)], as.factor) #https://stackoverflow.com/questions/20637360/convert-all-data-frame-character-columns-to-factors


levels(importance$year) <- c(2016, 2019)
levels(importance$vote_house) <- c('Liberal', 'Labor', 'National', 'Greens', 'Other', 'Informal', 'Christian Democratic', 'Family First', 'One Nation', "Palmer's United", "Katter's Australia", 'Liberal Democrats', 'Australian Sex', 'Nick Xenophon', 'Rise Up Australia', 'Australian Liberty Alliance', 'Animal Justice', 'Australian Conservatives', 'Independent')
levels(importance$importance_taxation) <- c('Extremely Important', 'Quite Important', 'Not Very Important')
levels(importance$importance_immigration) <- c('Extremely Important', 'Quite Important', 'Not Very Important')
levels(importance$importance_education) <- c('Extremely Important', 'Quite Important', 'Not Very Important')
levels(importance$importance_environment) <- c('Extremely Important', 'Quite Important', 'Not Very Important')
levels(importance$importance_debt) <- c('Extremely Important', 'Quite Important', 'Not Very Important')
levels(importance$importance_health) <- c('Extremely Important', 'Quite Important', 'Not Very Important')
levels(importance$importance_refugees) <- c('Extremely Important', 'Quite Important', 'Not Very Important')
levels(importance$importance_climate) <- c('Extremely Important', 'Quite Important', 'Not Very Important')
levels(importance$importance_superannuation) <- c('Extremely Important', 'Quite Important', 'Not Very Important')
levels(importance$importance_economy) <- c('Extremely Important', 'Quite Important', 'Not Very Important')
levels(importance$party_taxation) <- c('Labor', 'Liberal', 'No Difference')
levels(importance$party_immigration) <- c('Labor', 'Liberal', 'No Difference')
levels(importance$party_education) <- c('Labor', 'Liberal', 'No Difference')
levels(importance$party_environment) <- c('Labor', 'Liberal', 'No Difference')
levels(importance$party_debt) <- c('Labor', 'Liberal', 'No Difference')
levels(importance$party_health) <- c('Labor', 'Liberal', 'No Difference')
levels(importance$party_refugees) <- c('Labor', 'Liberal', 'No Difference')
levels(importance$party_climate) <- c('Labor', 'Liberal', 'No Difference')
levels(importance$party_superannuation) <- c('Labor', 'Liberal', 'No Difference')
levels(importance$party_economy) <- c('Labor', 'Liberal', 'No Difference')
levels(importance$issue_importance) <- c('Taxation', 'Immigration', 'Education', 'Environment', 'Debt', 'Health', 'Refugees', 'Climate', 'Superannuation', 'Economy')
levels(importance$issue_importance2) <- c('Taxation', 'Immigration', 'Education', 'Environment', 'Debt', 'Health', 'Refugees', 'Climate', 'Superannuation', 'Economy')
levels(importance$secondpref) <- c('Coalition', 'Labor')

liberal <- importance %>% filter(vote_house == 'Liberal' | vote_house == 'National')
labor <- importance %>% filter(vote_house == 'Labor')

liberal16 <- liberal %>% filter(year == 2016)
labor16 <- labor %>% filter(year == 2016)

liberal19 <- liberal %>% filter(year == 2019)
labor19 <- labor %>% filter(year == 2019)

importance
```

Create data sets specialised for demographics
```{r}
postcode <- restricted[,c(5, 11)]
demographics <- question_data[,c(1,2, 208, 220:222, 228, 235:237)]
demographics[,c(3,4,6:10)] <- demographics[,c(3,4,6:10)] %>% replace_with_na_all(condition = ~.x > 500)
demographics <- demographics %>% replace_with_na_all(condition = ~.x == 0)
demographics[,5] <- demographics[,5] %>% replace_with_na_all(condition = ~.x == 999)
demographics <- merge(demographics, postcode, by.x = 'Respondent_ID_2016', by.y = 'ID_2016')
demographics[sapply(demographics, is.numeric)] <- lapply(demographics[sapply(demographics, is.numeric)], as.factor)
demographics$birth_year <- as.numeric(format(as.Date(demographics$birth_year, format = '%Y'), '%Y'))
demographics <- na.omit(demographics)

levels(demographics$year) <- c(2016, 2019)
levels(demographics$qualifications) <- c('No Qualification', 'Postgraduate', 'Bachelor', 'Undergraduate', 'Associate Diploma', 'Trade', 'Non-Trade')
levels(demographics$sex) <- c('Male', 'Female', 'Other')
levels(demographics$birth_country) <- c('Australia', 'NESB', 'ESB')
levels(demographics$religion) <- c('Roman Catholic', 'Anglican', 'Methodist', 'Orthodox', 'Presbyterian', 'Other', 'No Religion', 'Catholic', 'Baptist', 'Churches of Christ', 'Lutheran', 'Salvation Army', 'Seventh Day Adventist', 'Protestant', 'Christian Other', 'Buddhist', 'Jewish', 'Muslim', 'Non-Christian Other', 'Hindu', 'Pentecostalism', 'Christian')
levels(demographics$social_class) <- c('Upper', 'Middle', 'Working', 'None')
levels(demographics$living_status) <- c('Rural', 'Small Country Town', 'Large Country Town', 'Large Town', 'Major City')
levels(demographics$annual_income) <- c('<10,000', '10,001-15,000', '15,001-20,000', '20,001-25,000', '25,001-30,000', '30,001-35,000', '35,001-40,000', '40,001-45,000', '45,001-50,000', '50,001-60,000', '60,001-70,000', '70,001-80,000', '80,001-90,000', '90,001-100,000', '100,001-110,000', '110,001-120,000', '120,001-130,000', '130,001-140,000', '140,001-150,000', '150,001-160,000', '160,001-180,000', '>180,000')

demographics$birth_year <- as.numeric(as.character(demographics$year)) - as.numeric(demographics$birth_year)
colnames(demographics)[5] <- 'age'

y2016 <- demographics %>% filter(year == 2016)
y2019 <- demographics %>% filter(year == 2019)

demographics
```

Combine demographic and issue data sets
```{r}
combined <- merge(importance, demographics, by = c('Respondent_ID_2016', 'year'))

labor2 <- combined %>% filter(vote_house == 'Labor'| secondpref == 'Labor')
labor2$vote_house <- c('Labor')
coalition <- combined %>% filter(vote_house == 'Liberal' | vote_house == 'National' | secondpref == 'Coalition')
coalition$vote_house <- c('Coalition')
twoparty <- rbind(labor2, coalition)
twoparty <- twoparty[-26]
twoparty

majorparties <- combined %>% filter(vote_house == 'Liberal' | vote_house == 'Labor' | vote_house == 'National' | vote_house == 'Greens')
```

```{r}
AusCodes <- australian_postcodes %>% select(postcode, locality, state, lat, long)
CodeFreq <- as.data.frame(table(demographics$PCODE))
colnames(CodeFreq) <- c('postcode', 'frequency')

AusCodes <- merge(AusCodes, CodeFreq, by.x = 'postcode', by.y = 'postcode')
AusCodes <- merge(AusCodes, PostcodePopulation, by.x = 'postcode', by.y = 'Postcode')
AusCodes
```

Datasets for Modelling
```{r}
modeldata2016 <- importance %>% filter(year == 2016)
modeldata2019 <- importance %>% filter(year == 2019)

modeldata2016 <- modeldata2016[,c(3:13)]
modeldata2019 <- modeldata2019[,c(3:13)]

twopartybase <- importance %>% filter(vote_house == 'Labor'| vote_house == 'Liberal')
twoparty1 <- twopartybase %>% filter(year == 2016)
twoparty2 <- twopartybase %>% filter(year == 2019)

modeldata2016 <- modeldata2016 %>% mutate(vote_house = replace(vote_house, c(vote_house != 'Labor' & vote_house != 'Liberal'), 'Other'))
modeldata2019 <- modeldata2019  %>% mutate(vote_house = replace(vote_house, c(vote_house != 'Labor' & vote_house != 'Liberal'), 'Other'))
```

Writing CSV files for portfolio
```{r}
write.csv(importance, 'Dataframes/importance.csv')
write.csv(liberal, 'Dataframes/Impliberal.csv')
write.csv(labor, 'Dataframes/Implabor.csv')
write.csv(liberal16, 'Dataframes/Impliberal16.csv')
write.csv(labor16, 'Dataframes/Implabor16.csv')
write.csv(liberal19, 'Dataframes/Impliberal19.csv')
write.csv(labor19, 'Dataframes/Implabor19.csv')
write.csv(demographics, 'Dataframes/demographics.csv')
write.csv(y2016, 'Dataframes/Demo16.csv')
write.csv(y2019, 'Dataframes/Demo19.csv')
write.csv(combined, 'Dataframes/combined.csv')
write.csv(twoparty, 'Dataframes/twoparty.csv')
write.csv(majorparties, 'Dataframes/majorparties.csv')
write.csv(AusCodes, 'Dataframes/Postcode.csv')
```

